version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://cp_user:secret123@db:5432/codigos_postales

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=codigos_postales
      - POSTGRES_USER=cp_user
      - POSTGRES_PASSWORD=secret123

volumes:
  postgres_data: