version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cp_user:secret123@db:5432/codigos_postales
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cp-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=codigos_postales
      - POSTGRES_USER=cp_user
      - POSTGRES_PASSWORD=secret123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cp_user -d codigos_postales"]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 10s
    networks:
      - cp-network

volumes:
  postgres_data:

networks:
  cp-network:
    driver: bridge

# Configuración opcional para PgAdmin (descomentar si se necesita)
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@cp.com
#      - PGADMIN_DEFAULT_PASSWORD=admin123
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
#    networks:
#      - cp-network